using Microsoft.EntityFrameworkCore.Migrations;

namespace YouTubeCleanupTool.DataAccess.Migrations
{
    public partial class TrueupPlaylistItemDatasoitnolongerhasautogeneratedcolumn : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_PlaylistItems_Videos_VideoDataId",
                table: "PlaylistItems");

            migrationBuilder.DropIndex(
                name: "IX_PlaylistItems_VideoDataId",
                table: "PlaylistItems");

            migrationBuilder.DropColumn(
                name: "VideoDataId",
                table: "PlaylistItems");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "VideoDataId",
                table: "PlaylistItems",
                type: "TEXT",
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "IX_PlaylistItems_VideoDataId",
                table: "PlaylistItems",
                column: "VideoDataId");

            migrationBuilder.AddForeignKey(
                name: "FK_PlaylistItems_Videos_VideoDataId",
                table: "PlaylistItems",
                column: "VideoDataId",
                principalTable: "Videos",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);
        }
    }
}
